### ISSUE TITLE
Optimized for new ARM cores

### ISSUE THREAD

**Issue by chuvitvang** [Oink70/CCminer-ARM-optimized#6]
Is it only optimized on Cortex A55 and A53?, can you optimize for other Cortex models like A75 A76? thank you!

**Comment by Oink70** [comment]
Optimizing for A75 doesn't bring performance increase over A53. The same goes for A76 & A55.
Running A75/A76 optimized miners actually detract from A53/A55 cores performance.

In case you contemplate running separate miners for separate cores: the added overhead results in (slightly) decreased performance.

I did extensive testing on the above scenarios and for me it's non-sensical to release separate binaries that do not increase or even have the possibility to decrease your performance.
