### ISSUE TITLE
BEWARE CHEATING-ALWAYS HAVE (null) output by tail -f log (null)

### ISSUE THREAD

**Issue by zubah** [Oink70/CCminer-ARM-optimized#9]
*  ccminer CPU: 3.8.3-4 for Verushash v2.2 based on ccminer   *
2|ccminer- | ***************************************************************
2|ccminer- | Originally based on Christian Buchner and Christian H. project
2|ccminer- | Adapted to Verus by Monkins1010
2|ccminer- | Adapted for ARM optimization by Mixed-Nuts
2|ccminer- | Adapted and compiled by Oink.vrsc@
2|ccminer- | Goto https://wiki.verus.io/#!index.md for mining setup guides.
2|ccminer- | Git repo located at: http://github.com/monkins1010/ccminer
2|ccminer- |
2|ccminer- | [2024-08-23 16:01:26] 4 miner threads started, using 'verus' algorithm.
2|ccminer- | [2024-08-23 16:01:26] Starting on stratum+tcp://ap.luckpool.net:3960

2|ccminer-3.8.3-4_ARM  | [2024-08-23 16:01:27] Stratum difficulty set to 524280
2|ccminer-3.8.3-4_ARM  | [2024-08-23 16:01:50] CPU T2: Verus Hashing. (null), 314.54 kH/s
2|ccminer-3.8.3-4_ARM  | [2024-08-23 16:01:51] accepted: 1/1 (diff 4325310.000), 314.54 kH/s yes!
2|ccminer-3.8.3-4_ARM  | [2024-08-23 16:02:38] Stratum difficulty set to 262140
2|ccminer-3.8.3-4_ARM  | [2024-08-23 16:02:39] CPU T2: Verus Hashing. (null), 286.66 kH/s

###############################NOTE-WARNING-NOTE#######################################

###############################LOOK-THIS#############AFFAIR-OR-CHEATING##################
(null) and (null) what happend with (null) ?? What's it (null) not full Hashing? and I thing this using by Developer, and using by another worker

**Comment by xORCAx** [comment]
So what is actually? I'm curious.
